### ISSUE TITLE
Don't Use mavenLocal

### ISSUE THREAD

**Issue by opticyclic** [corda/cordapp-tutorial#131]
In the `build.gradle` here and in nearly all your samples you put mavenLocal at the top of your repo list.

What are you trying to achieve with this?

Gradle will cache items anyway so you don't need it for that reason.

On the other hand, if you have an item in your maven local that is not published (or is different from what is published) then the build will work for you but not when other people run it.

So at best it looks redundant and at worst it seems dangerous.

**Comment by joeldudley** [comment]
One good case where you'd want to use mavenLocal is if you make a change to Corda, then publish it locally to run your CorDapp against your modified Corda version.

**Comment by Clintonio** [comment]
To add to this it is a responsibility of the developer or team working on their Cordapp to define their build.gradle and understand it. 

Though for this example, which was/is generally intended to be the minimal amount of code to show how to get a Cordapp working, it it a superfluous line. Not because it's dangerous though. A PR to remove it for that reason is welcome.
